name: OpenWrt-CI-HC5861

on:
  schedule:
    - cron: '0 20 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_openwrt:
    name: Build OpenWrt Firmware for HiWiFi HC5861
    runs-on: ubuntu-22.04

    steps:
      - name: Cleanup and setup environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q) || true
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android || true
          sudo -E apt-mark hold grub-efi-amd64-signed || true
          sudo -E apt update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap* || true
          sudo -E apt -y full-upgrade
          sudo -E apt -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Checkout OpenWrt source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone Passwall2 package
        run: |
          git clone --depth=1 https://github.com/xiaorouji/openwrt-passwall2.git package/passwall2

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate minimal config for HC5861 with Passwall2 + SingBox + Chinese UI
        run: |
          rm -f .config
          echo "CONFIG_TARGET_ramips=y" >> .config
          echo "CONFIG_TARGET_ramips_mt7620=y" >> .config
          echo "CONFIG_TARGET_ramips_mt7620_DEVICE_hiwifi_hc5861=y" >> .config

          echo "CONFIG_PACKAGE_luci-app-passwall2=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_SingBox=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Xray=n" >> .config
          echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_V2ray=n" >> .config
          echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Trojan=n" >> .config
          echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Shadowsocks_Libev_Client=n" >> .config
          echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_ShadowsocksR_Libev_Client=n" >> .config

          echo "CONFIG_PACKAGE_luci-i18n-base-zh-cn=y" >> .config
          echo "CONFIG_PACKAGE_luci-i18n-passwall2-zh-cn=y" >> .config
          echo "CONFIG_PACKAGE_luci-i18n-base-en=n" >> .config
          echo "CONFIG_PACKAGE_luci-i18n-passwall2-en=n" >> .config

          echo "CONFIG_PACKAGE_ipv6helper=n" >> .config
          echo "CONFIG_PACKAGE_luci-proto-ipv6=n" >> .config
          echo "CONFIG_PACKAGE_odhcp6c=n" >> .config
          echo "CONFIG_PACKAGE_odhcpd-ipv6only=n" >> .config

          echo "CONFIG_PACKAGE_ppp=n" >> .config
          echo "CONFIG_PACKAGE_ppp-mod-pppoe=n" >> .config

          echo "CONFIG_PACKAGE_kmod-usb-core=n" >> .config
          echo "CONFIG_PACKAGE_kmod-usb-ohci=n" >> .config
          echo "CONFIG_PACKAGE_kmod-usb2=n" >> .config
          echo "CONFIG_PACKAGE_kmod-usb-storage=n" >> .config
          echo "CONFIG_PACKAGE_kmod-fs-ext4=n" >> .config
          echo "CONFIG_PACKAGE_block-mount=n" >> .config
          echo "CONFIG_PACKAGE_mount-utils=n" >> .config

          echo "CONFIG_PACKAGE_zram-swap=y" >> .config
          echo "CONFIG_KERNEL_ZSWAP_COMPRESSOR_DEFAULT=lz4" >> .config

          echo "CONFIG_STRIP_KERNEL_EXPORTS=y" >> .config
          echo "CONFIG_KERNEL_DEBUG_INFO=n" >> .config
          echo "CONFIG_KERNEL_KALLSYMS=n" >> .config

          echo "CONFIG_TARGET_IMAGES_GZIP=y" >> .config
          echo "CONFIG_TARGET_ROOTFS_SQUASHFS=y" >> .config
          echo "CONFIG_TARGET_ROOTFS_IMAGES=squashfs" >> .config

          echo "CONFIG_BUSYBOX_CUSTOM=y" >> .config
          echo "CONFIG_BUSYBOX_CONFIG_FEATURE_IPV6=n" >> .config

          make defconfig

      - name: Remove unused LuCI language packs except zh-cn
        run: |
          find feeds/luci/modules/luci-base/po/ -maxdepth 1 -type d ! -name "zh-cn" ! -name "po" -exec rm -rf {} +
          find feeds/luci/applications/ -type d -path "*/po/*" ! -name "zh-cn" -exec rm -rf {} +

      - name: Download all required packages
        run: make download -j$(nproc)

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: Compress SingBox binary with UPX (max compression)
        run: |
          find ./build_dir/ -type f -name "sing-box" -exec upx --best --lzma {} \; || echo "No sing-box binary found"

      - name: Prepare artifacts (firmware + packages)
        run: |
          mkdir -p ./artifact
          tar -czf ./artifact/firmware.tar.gz -C ./bin/targets .
          mkdir -p ./artifact/package
          find ./bin/packages/ -type f -name "*.ipk" -exec cp -f {} ./artifact/package/ \; || true

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_firmware
          path: ./artifact/firmware.tar.gz

      - name: Upload packages artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_packages
          path: ./artifact/package/
