name: Build OpenWrt Firmware for HiWiFi HC5861 Minimal SSR Client

on:
  schedule:
    - cron: '0 20 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_openwrt:
    name: Build OpenWrt Firmware for HiWiFi HC5861 Minimal SSR Client
    runs-on: ubuntu-22.04

    steps:
      - name: Setup build environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential libncurses5-dev gawk git subversion \
            unzip zlib1g-dev libssl-dev wget python3 python3-distutils \
            curl ccache gettext libz-dev file
          sudo timedatectl set-timezone Asia/Shanghai

      - name: Checkout OpenWrt source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure build for HC5861 minimal SSR client
        run: |
          cat > .config <<EOF
CONFIG_TARGET_ramips=y
CONFIG_TARGET_ramips_mt7620=y
CONFIG_TARGET_ramips_mt7620_DEVICE_hiwifi_hc5861=y

CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-base=y
CONFIG_PACKAGE_luci-ssl=y
CONFIG_PACKAGE_luci-i18n-base-zh-cn=y

CONFIG_PACKAGE_shadowsocks-libev-ss-local=y
CONFIG_PACKAGE_luci-app-simple-ssr=y

CONFIG_PACKAGE_ipv6helper=n
CONFIG_PACKAGE_luci-proto-ipv6=n
CONFIG_PACKAGE_odhcp6c=n
CONFIG_PACKAGE_odhcpd-ipv6only=n

CONFIG_PACKAGE_kmod-usb-core=n
CONFIG_PACKAGE_kmod-usb-ohci=n
CONFIG_PACKAGE_kmod-usb2=n
CONFIG_PACKAGE_kmod-usb-storage=n
CONFIG_PACKAGE_kmod-fs-ext4=n
CONFIG_PACKAGE_block-mount=n
CONFIG_PACKAGE_mount-utils=n

CONFIG_KERNEL_DEBUG_INFO=n
CONFIG_STRIP_KERNEL_EXPORTS=y

CONFIG_TARGET_IMAGES_GZIP=y
CONFIG_TARGET_ROOTFS_SQUASHFS=y
CONFIG_TARGET_ROOTFS_IMAGES=squashfs

CONFIG_BUSYBOX_CUSTOM=y
CONFIG_BUSYBOX_CONFIG_FEATURE_IPV6=n

EOF
          make defconfig

      - name: Remove unnecessary language packs to save space
        run: |
          find feeds/luci/modules/luci-base/po/ -maxdepth 1 -type d ! -name "zh-cn" ! -name "po" -exec rm -rf {} +
          find feeds/luci/applications/ -type d -path "*/po/*" ! -name "zh-cn" -exec rm -rf {} +

      - name: Download all required packages
        run: make download -j$(nproc)

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: Prepare artifacts (firmware + packages)
        run: |
          mkdir -p ./artifact
          tar -czf ./artifact/firmware.tar.gz -C ./bin/targets .
          mkdir -p ./artifact/package
          find ./bin/packages/ -type f -name "*.ipk" -exec cp -f {} ./artifact/package/ \; || true

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_firmware
          path: ./artifact/firmware.tar.gz

      - name: Upload packages artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_packages
          path: ./artifact/package/
